CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250901061936_InitialCreate') THEN
    CREATE TABLE "Versions" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProjectId" bigint NOT NULL,
        "IdentifierName" character varying(200) NOT NULL,
        "ReleaseNumber" character varying(100) NOT NULL,
        "Meta" character varying(200),
        "LastUpdated" text NOT NULL,
        "ConcurrencyToken" uuid NOT NULL,
        CONSTRAINT "PK_Versions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250901061936_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Versions_ProjectId_IdentifierName" ON "Versions" ("ProjectId", "IdentifierName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250901061936_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250901061936_InitialCreate', '9.0.8');
    END IF;
END $EF$;
COMMIT;

